# Generated by ChatGPT
from typing import Dict, List, Tuple

import torch
import torch.nn as nn
from torch.nn.parameter import Parameter


class YogiBackprop(nn.Module):
    moment1: Dict[str, torch.Tensor] = torch.jit.Attribute({}, Dict[str, torch.Tensor])
    moment2: Dict[str, torch.Tensor] = torch.jit.Attribute({}, Dict[str, torch.Tensor])

    def __init__(self, step_size: float = 0.01, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-3):
        super(YogiBackprop, self).__init__()
        self.step_size = step_size
        self.beta1 = beta1
        self.beta2 = beta2
        self.eps = eps
        self.step = 0
        self.moment1: Dict[str, torch.Tensor] = {}
        self.moment2: Dict[str, torch.Tensor] = {}

    def forward(
        self, loss: torch.Tensor, prev_loss: torch.Tensor, named_parameters: List[Tuple[str, Parameter]]
    ) -> Dict[str, torch.Tensor]:
        self.step += 1
        params = [param for _, param in named_parameters]
        grads = torch.autograd.grad([loss], params, create_graph=False, allow_unused=True)

        new_params: Dict[str, torch.Tensor] = {}

        for (name, param), grad in zip(named_parameters, grads):
            if grad is None:
                grad = torch.zeros_like(param)

            if name not in self.moment1:
                self.moment1[name] = torch.zeros_like(param)
                self.moment2[name] = torch.full_like(param, self.eps)
            m = self.moment1[name]
            v = self.moment2[name]

            m = self.beta1 * m + (1 - self.beta1) * grad

            # Yogi second moment update
            diff = v - grad * grad
            v = v + (1 - self.beta2) * (grad * grad) * torch.sign(diff)

            # Bias-correct moments (optional, here used for first moment)
            m_hat = m / (1 - self.beta1**self.step)

            # Update parameter
            new_params[name] = param - self.step_size * (m_hat / (torch.sqrt(v) + self.eps))

            self.moment1[name] = m
            self.moment2[name] = v

        return new_params


if __name__ == "__main__":
    optimizer = torch.jit.script(YogiBackprop())
    torch.jit.save(optimizer, __file__.replace(".py", ".pt"))
    print(optimizer.graph)
